### ISSUE TITLE
Release stable version?

### ISSUE THREAD

**Issue by nylen** [nylen/phpegjs#8]
#2 was the last outstanding issue I was aware of, so I think we could release v1.0.0 now (or maybe `1.10.0` to mirror the compatible PEG.js version, `0.10.0`).

Another thing to wait for would be a PEG.js `0.11.0` release, since they've had [a lot of changes](https://github.com/pegjs/pegjs/compare/v0.10.0...1b2072f) since v0.10.0.

cc @aduth, what do you think?

**Comment by aduth** [comment]
I don't have strong feelings one way or the other between `v1.0.0` stable, or a `v1.0.0-beta8` in anticipation of PEG.js `0.11.0`.

A `1.10.0` would be a bit awkward though, since it doesn't really adhere to expected SemVer.

**Comment by mevtho** [comment]
Hi,

Sorry for replying to an old issue, but it seems related. 

Could you publish a new version as it seems that the version available from npm doesn't have the code from 2017 fixing the text() function.

#2 

On a new install, I get :

```
> mkdir test
> cd test
> npm install phpegjs
> npm ls phpegjs
test
└── phpegjs@1.0.0-beta7 

> cat -n node_modules/phpegjs/src/passes/generate-php.js | grep 65[0,1,2]
   650	        '    private function text() {',
   651	        '      return substr($this->input, $this->peg_reportedPos, $this->peg_reportedPos + $this->peg_currPos);',
   652	        '    }',
 
```

When the expected lines for the text function would be :
```
        '    private function text() {',
        '      return $this->input_substr($this->peg_reportedPos, $this->peg_currPos - $this->peg_reportedPos);',
        '    }',
```

It is easy enough to fix manually in the generated php though.

Thank you.
